# Generated by Django 6.0.3 on 2026-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=5)),
            ],
        ),
    ]
