# Generated by Django 6.0.3 on 2026-05-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=20)),
                ('cie_marks', models.IntegerField()),
            ],
        ),
    ]
